version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    working_dir: /backend
    restart: on-failure
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload'
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${DB_ROOT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5436:5432
    volumes:
      - ./data:/var/lib/postgresql/data